### login
@url_dev=http://localhost:3000/v1/api  
POST {{url_dev}}/product
Content-Type: application/json
x-api-key: eb13f5ba9c630690d727366e3ed642ec3544c16f0d49b17c9944fc393fdbea7700dfecb1ed77a5d811bf1441092e787227e2056733a52f208c0449122cac9a47
x-client-id : 65b8669e984e8bd12f27664b
x-access-token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWI4NjY5ZTk4NGU4YmQxMmYyNzY2NGIiLCJlbWFpbCI6InNob3BBMUBnbWFpbC5jb20iLCJpYXQiOjE3MDY2MDkwNjMsImV4cCI6MTcwNjc4MTg2M30.w-39baSwTmLV4aH8cgpU4KexoQHxsdwMvAmjhoonOuo

{
    "productName" : "Jean luxury",
    "productThumb" : "https://www.google.com/imgres?imgurl=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1523275335684-37898b6baf30%3Fq%3D80%26w%3D1000%26auto%3Dformat%26fit%3Dcrop%26ixlib%3Drb-4.0.3%26ixid%3DM3wxMjA3fDB8MHxzZWFyY2h8Mnx8cHJvZHVjdHxlbnwwfHwwfHx8MA%253D%253D&tbnid=TInYQSGcrLQY4M&vet=12ahUKEwjVk-6C8veDAxXgka8BHSmCBVAQMygAegQIARBz..i&imgrefurl=https%3A%2F%2Funsplash.com%2Fs%2Fphotos%2Fproduct&docid=Bfa8p_BERHYMYM&w=1000&h=726&q=image%20product%20image&ved=2ahUKEwjVk-6C8veDAxXgka8BHSmCBVAQMygAegQIARBz",
    "productDescription": "description product",
    "productPrice":2000,
    "productQuantity":10,
    "productType" : "Clothing",
    "productShop" : "65b8669e984e8bd12f27664b",
    "productAttributes": {
        "brand":"Coolmate",
        "size": "M",
        "material":"Cotton 100%"
    }
}



